#!/usr/bin/env bash
# Install a system-recognised .desktop launcher for FormatLab so the app
# shows up in the Cinnamon (and GNOME/KDE/XFCE) application menu with a
# proper icon, and can be pinned to the taskbar.
#
# Usage:
#   ./scripts/install-desktop-entry.sh             # auto-detect icon
#   ./scripts/install-desktop-entry.sh /path/icon  # use custom icon path
#
# Re-run this after moving the project folder to refresh paths.

set -euo pipefail

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &>/dev/null && pwd )"
PROJECT_DIR="$( cd -- "${SCRIPT_DIR}/.." &>/dev/null && pwd )"

LAUNCHER="${PROJECT_DIR}/scripts/launch-formatlab.sh"
DEV_LAUNCHER="${PROJECT_DIR}/scripts/launch-formatlab-dev.sh"
TEMPLATE="${PROJECT_DIR}/scripts/formatlab.desktop.template"
DEV_TEMPLATE="${PROJECT_DIR}/scripts/formatlab-dev.desktop.template"

# Pick an icon in this order of preference:
#   1. explicit argument
#   2. ~/Pictures/format_lab_logo.png (the custom icon Caleb uses)
#   3. the 128x128 PNG generated by `tauri icon`
#   4. the source app-icon.png
USER_ICON="${1-}"
if [[ -n "${USER_ICON}" && -f "${USER_ICON}" ]]; then
    ICON="${USER_ICON}"
elif [[ -f "${HOME}/Pictures/format_lab_logo.png" ]]; then
    ICON="${HOME}/Pictures/format_lab_logo.png"
elif [[ -f "${PROJECT_DIR}/src-tauri/icons/128x128.png" ]]; then
    ICON="${PROJECT_DIR}/src-tauri/icons/128x128.png"
elif [[ -f "${PROJECT_DIR}/app-icon.png" ]]; then
    ICON="${PROJECT_DIR}/app-icon.png"
else
    echo "No icon found. Pass one as an argument: $0 /path/to/icon.png" >&2
    exit 1
fi

chmod +x "${LAUNCHER}" "${DEV_LAUNCHER}"

APPS_DIR="${HOME}/.local/share/applications"
mkdir -p "${APPS_DIR}"

# Main entry — smart launcher (runs release binary, builds if missing).
MAIN_DEST="${APPS_DIR}/formatlab.desktop"
sed \
    -e "s|__EXEC__|${LAUNCHER}|g" \
    -e "s|__ICON__|${ICON}|g" \
    "${TEMPLATE}" > "${MAIN_DEST}"
chmod +x "${MAIN_DEST}"

# Dev entry — hot-reload launcher, hidden from casual users but kept
# around for times when you're iterating on code.
DEV_DEST="${APPS_DIR}/formatlab-dev.desktop"
sed \
    -e "s|__EXEC__|${DEV_LAUNCHER}|g" \
    -e "s|__ICON__|${ICON}|g" \
    "${DEV_TEMPLATE}" > "${DEV_DEST}"
chmod +x "${DEV_DEST}"

# Refresh the app-menu cache so entries appear without a logout/login.
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "${APPS_DIR}" 2>/dev/null || true
fi

echo "Installed FormatLab launchers:"
echo "  Main entry     : ${MAIN_DEST}"
echo "  Launcher       : ${LAUNCHER}"
echo "  Dev entry      : ${DEV_DEST}"
echo "  Dev launcher   : ${DEV_LAUNCHER}"
echo "  Icon           : ${ICON}"
echo ""
echo "You can now:"
echo "  • Find 'FormatLab' in your application menu (normal use)"
echo "  • Find 'FormatLab (Dev)' in the menu for hot-reload dev mode"
echo "  • Right-click either entry and pin it to the panel/taskbar"
echo "  • Drag the main .desktop file to your Desktop for a shortcut"
